### ISSUE TITLE
Issue in Todo list related to local Storage.

### ISSUE THREAD

**Issue by Laraib-Azmat** [Laraib-Azmat/Todo-list#1]
I have an issue in todo list as when I reload my web page everything works fine e.g. local Storage  but the completed tasks  are not still completed as **I give a class of completed to that tasks which I marked as check/completed but after reload these are not with completed class** I want to fix this issue. Here is JavaScript file -> https://github.com/Laraib-Azmat/Todo-list/commit/718630e1460ce14734197fe92023825d3e3c83fb

**Comment by ZainEjaz24** [comment]
I Can Solve the Issue of Local Storage

**Comment by Laraib-Azmat** [comment]
Okay Thank you

**Comment by ZainEjaz24** [comment]
You're Welcome & Thank You for assigning it to me
